name: Build and Release EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller autopep8 PyQt5 PyQtWebEngine

    - name: Auto-fix Python Indentation
      run: |
        autopep8 --in-place --aggressive --aggressive main.py

    - name: Build Single EXE (Bản 1 file chống lỗi giải nén)
      run: |
        # Thêm --collect-all PyQt5 và --collect-all PyQtWebEngine để gom toàn bộ file DLL chuẩn
        pyinstaller --onefile --noconsole --name "yt-tv-in-windows" --collect-all PyQt5 --collect-all PyQtWebEngine main.py

    - name: Build Directory (Bản nhiều file)
      run: |
        pyinstaller --noconsole --name "yt-tv-in-windows-folder" --distpath ./dist-folder --collect-all PyQt5 --collect-all PyQtWebEngine main.py

    - name: Create ZIP
      run: |
        if (!(Test-Path dist)) { New-Item -ItemType Directory -Path dist }
        Compress-Archive -Path ./dist-folder/yt-tv-in-windows-folder/* -DestinationPath ./dist/yt-tv-in-windows.zip

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "1.0.1"
        name: "Release v1.0.1"
        draft: false
        prerelease: false
        make_latest: true
        files: |
          dist/yt-tv-in-windows.exe
          dist/yt-tv-in-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
